#!/usr/bin/env python3
"""Regenerate shims/OpenGL/ShackGLFunctions.h: every gl* symbol the macOS SDK's OpenGL.framework exports, as an X-macro list.
ShackOpenGL.c exports a lazy trampoline for each, so a native arm64 game that links OpenGL.framework binds at load time.
Run: python3 prep/gen_gl_functions.py [macos-sdk-path]   (default: xcrun --sdk macosx --show-sdk-path)"""
import pathlib
import re
import subprocess
import sys

DEFINED_IN_SHACKOPENGL_C = {"glFenceSync", "glClientWaitSync", "glDeleteSync", "glFlush"}   # real functions there already
root = pathlib.Path(__file__).resolve().parents[1]
sdk = sys.argv[1] if len(sys.argv) > 1 else subprocess.check_output(["xcrun", "--sdk", "macosx", "--show-sdk-path"], text=True).strip()
tbd = (pathlib.Path(sdk) / "System/Library/Frameworks/OpenGL.framework/OpenGL.tbd").read_text()
names = sorted({m[1:] for m in re.findall(r"'?(_gl[A-Za-z0-9_]+)'?", tbd)} - DEFINED_IN_SHACKOPENGL_C)
out = root / "shims/OpenGL/ShackGLFunctions.h"
lines = ["// Generated by prep/gen_gl_functions.py from the macOS SDK's OpenGL.tbd. Do not edit.", "#define SHACK_GL_FUNCTIONS(X) \\"]
lines += [f"    X({n}) \\" for n in names]
lines.append("    /* end */")
out.write_text("\n".join(lines) + "\n")
print(f"{len(names)} functions -> {out}")
