// GENERATED by prep/steam-onehost/gen_stubs.py from prep/steam-onehost/ios-link-gaps.txt; do not edit.
// libShackSteamClient: what the macOS Steam client imports that iOS and MacShack's shims lack.
#import <Foundation/Foundation.h>
#import <os/log.h>

void ShackSteamStubCalled(const char *name) { os_log(OS_LOG_DEFAULT, "[SteamClient] stub called: %{public}s", name); }

// Stub classes answer any message through libShackAppKit's safety net (logged once, returns 0/nil).
NSMethodSignature *ShackStubSignature(SEL sel);
void ShackStubInvoke(id self, NSInvocation *inv);
#define STUB_SAFETY_NET \
- (NSMethodSignature *)methodSignatureForSelector:(SEL)s { return [super methodSignatureForSelector:s] ?: ShackStubSignature(s); } \
- (void)forwardInvocation:(NSInvocation *)i { ShackStubInvoke(self, i); } \
+ (NSMethodSignature *)methodSignatureForSelector:(SEL)s { return [super methodSignatureForSelector:s] ?: ShackStubSignature(s); } \
+ (void)forwardInvocation:(NSInvocation *)i { ShackStubInvoke(self, i); }

NSString *const NSAccessibilityApplicationActivatedNotification = @"AXApplicationActivated";
NSString *const NSAccessibilityApplicationDeactivatedNotification = @"AXApplicationDeactivated";
NSString *const NSAccessibilityApplicationHiddenNotification = @"AXApplicationHidden";
NSString *const NSAccessibilityApplicationShownNotification = @"AXApplicationShown";
NSString *const NSAccessibilityAscendingSortDirectionValue = @"AXAscendingSortDirection";
NSString *const NSAccessibilityAttributedStringForRangeParameterizedAttribute = @"AXAttributedStringForRange";
NSString *const NSAccessibilityBackgroundColorTextAttribute = @"AXBackgroundColor";
NSString *const NSAccessibilityBoundsForRangeParameterizedAttribute = @"AXBoundsForRange";
NSString *const NSAccessibilityCancelAction = @"AXCancel";
NSString *const NSAccessibilityCellForColumnAndRowParameterizedAttribute = @"AXCellForColumnAndRow";
NSString *const NSAccessibilityChildrenAttribute = @"AXChildren";
NSString *const NSAccessibilityColumnHeaderUIElementsAttribute = @"AXColumnHeaderUIElements";
NSString *const NSAccessibilityColumnIndexRangeAttribute = @"AXColumnIndexRange";
NSString *const NSAccessibilityColumnRole = @"AXColumn";
NSString *const NSAccessibilityColumnsAttribute = @"AXColumns";
NSString *const NSAccessibilityContentListSubrole = @"AXContentList";
NSString *const NSAccessibilityContentsAttribute = @"AXContents";
NSString *const NSAccessibilityCreatedNotification = @"AXCreated";
NSString *const NSAccessibilityDecrementAction = @"AXDecrement";
NSString *const NSAccessibilityDefinitionListSubrole = @"AXDefinitionList";
NSString *const NSAccessibilityDescendingSortDirectionValue = @"AXDescendingSortDirection";
NSString *const NSAccessibilityDescriptionAttribute = @"AXDescription";
NSString *const NSAccessibilityDisclosedByRowAttribute = @"AXDisclosedByRow";
NSString *const NSAccessibilityDisclosedRowsAttribute = @"AXDisclosedRows";
NSString *const NSAccessibilityDisclosingAttribute = @"AXDisclosing";
NSString *const NSAccessibilityDisclosureLevelAttribute = @"AXDisclosureLevel";
NSString *const NSAccessibilityDrawerCreatedNotification = @"AXDrawerCreated";
NSString *const NSAccessibilityEnabledAttribute = @"AXEnabled";
NSString *const NSAccessibilityExpandedAttribute = @"AXExpanded";
NSString *const NSAccessibilityFocusedAttribute = @"AXFocused";
NSString *const NSAccessibilityFocusedWindowChangedNotification = @"AXFocusedWindowChanged";
NSString *const NSAccessibilityFontSizeKey = @"AXFontSize";
NSString *const NSAccessibilityFontTextAttribute = @"AXFont";
NSString *const NSAccessibilityForegroundColorTextAttribute = @"AXForegroundColor";
NSString *const NSAccessibilityGridRole = @"AXGrid";
NSString *const NSAccessibilityHeaderAttribute = @"AXHeader";
NSString *const NSAccessibilityHelpAttribute = @"AXHelp";
NSString *const NSAccessibilityHelpTagCreatedNotification = @"AXHelpTagCreated";
NSString *const NSAccessibilityHelpTagRole = @"AXHelpTag";
NSString *const NSAccessibilityHorizontalOrientationValue = @"AXHorizontalOrientation";
NSString *const NSAccessibilityIncrementAction = @"AXIncrement";
NSString *const NSAccessibilityIndexAttribute = @"AXIndex";
NSString *const NSAccessibilityInsertionPointLineNumberAttribute = @"AXInsertionPointLineNumber";
NSString *const NSAccessibilityLineForIndexParameterizedAttribute = @"AXLineForIndex";
NSString *const NSAccessibilityLinkedUIElementsAttribute = @"AXLinkedUIElements";
NSString *const NSAccessibilityMainWindowChangedNotification = @"AXMainWindowChanged";
NSString *const NSAccessibilityMarkedMisspelledTextAttribute = @"AXMarkedMisspelled";
NSString *const NSAccessibilityMaxValueAttribute = @"AXMaxValue";
NSString *const NSAccessibilityMinValueAttribute = @"AXMinValue";
NSString *const NSAccessibilityMovedNotification = @"AXMoved";
NSString *const NSAccessibilityNumberOfCharactersAttribute = @"AXNumberOfCharacters";
NSString *const NSAccessibilityOrientationAttribute = @"AXOrientation";
NSString *const NSAccessibilityParentAttribute = @"AXParent";
NSString *const NSAccessibilityPlaceholderValueAttribute = @"AXPlaceholderValue";
NSString *const NSAccessibilityPositionAttribute = @"AXPosition";
NSString *const NSAccessibilityPressAction = @"AXPress";
NSString *const NSAccessibilityRTFForRangeParameterizedAttribute = @"AXRTFForRange";
NSString *const NSAccessibilityRangeForIndexParameterizedAttribute = @"AXRangeForIndex";
NSString *const NSAccessibilityRangeForLineParameterizedAttribute = @"AXRangeForLine";
NSString *const NSAccessibilityRangeForPositionParameterizedAttribute = @"AXRangeForPosition";
NSString *const NSAccessibilityRequiredAttribute = @"AXRequired";
NSString *const NSAccessibilityResizedNotification = @"AXResized";
NSString *const NSAccessibilityRoleAttribute = @"AXRole";
NSString *const NSAccessibilityRoleDescriptionAttribute = @"AXRoleDescription";
NSString *const NSAccessibilityRowCollapsedNotification = @"AXRowCollapsed";
NSString *const NSAccessibilityRowCountChangedNotification = @"AXRowCountChanged";
NSString *const NSAccessibilityRowExpandedNotification = @"AXRowExpanded";
NSString *const NSAccessibilityRowHeaderUIElementsAttribute = @"AXRowHeaderUIElements";
NSString *const NSAccessibilityRowIndexRangeAttribute = @"AXRowIndexRange";
NSString *const NSAccessibilityRowsAttribute = @"AXRows";
NSString *const NSAccessibilitySelectedAttribute = @"AXSelected";
NSString *const NSAccessibilitySelectedCellsChangedNotification = @"AXSelectedCellsChanged";
NSString *const NSAccessibilitySelectedChildrenAttribute = @"AXSelectedChildren";
NSString *const NSAccessibilitySelectedChildrenChangedNotification = @"AXSelectedChildrenChanged";
NSString *const NSAccessibilitySelectedChildrenMovedNotification = @"AXSelectedChildrenMoved";
NSString *const NSAccessibilitySelectedColumnsChangedNotification = @"AXSelectedColumnsChanged";
NSString *const NSAccessibilitySelectedRowsAttribute = @"AXSelectedRows";
NSString *const NSAccessibilitySelectedTextAttribute = @"AXSelectedText";
NSString *const NSAccessibilitySelectedTextRangeAttribute = @"AXSelectedTextRange";
NSString *const NSAccessibilitySheetCreatedNotification = @"AXSheetCreated";
NSString *const NSAccessibilityShowMenuAction = @"AXShowMenu";
NSString *const NSAccessibilitySizeAttribute = @"AXSize";
NSString *const NSAccessibilitySortDirectionAttribute = @"AXSortDirection";
NSString *const NSAccessibilityStrikethroughTextAttribute = @"AXStrikethrough";
NSString *const NSAccessibilityStringForRangeParameterizedAttribute = @"AXStringForRange";
NSString *const NSAccessibilityStyleRangeForIndexParameterizedAttribute = @"AXStyleRangeForIndex";
NSString *const NSAccessibilitySubroleAttribute = @"AXSubrole";
NSString *const NSAccessibilityTabsAttribute = @"AXTabs";
NSString *const NSAccessibilityTitleAttribute = @"AXTitle";
NSString *const NSAccessibilityTitleUIElementAttribute = @"AXTitleUIElement";
NSString *const NSAccessibilityTopLevelUIElementAttribute = @"AXTopLevelUIElement";
NSString *const NSAccessibilityURLAttribute = @"AXURL";
NSString *const NSAccessibilityUnderlineTextAttribute = @"AXUnderline";
NSString *const NSAccessibilityUnitsChangedNotification = @"AXUnitsChanged";
NSString *const NSAccessibilityUnknownSortDirectionValue = @"AXUnknownSortDirection";
NSString *const NSAccessibilityValueAttribute = @"AXValue";
NSString *const NSAccessibilityValueDescriptionAttribute = @"AXValueDescription";
NSString *const NSAccessibilityVerticalOrientationValue = @"AXVerticalOrientation";
NSString *const NSAccessibilityVisibleCellsAttribute = @"AXVisibleCells";
NSString *const NSAccessibilityVisibleCharacterRangeAttribute = @"AXVisibleCharacterRange";
NSString *const NSAccessibilityVisibleChildrenAttribute = @"AXVisibleChildren";
NSString *const NSAccessibilityVisibleColumnsAttribute = @"AXVisibleColumns";
NSString *const NSAccessibilityVisibleRowsAttribute = @"AXVisibleRows";
NSString *const NSAccessibilityWindowAttribute = @"AXWindow";
NSString *const NSAccessibilityWindowCreatedNotification = @"AXWindowCreated";
NSString *const NSAccessibilityWindowDeminiaturizedNotification = @"AXWindowDeminiaturized";
NSString *const NSAccessibilityWindowMiniaturizedNotification = @"AXWindowMiniaturized";
NSString *const NSAccessibilityWindowMovedNotification = @"AXWindowMoved";
NSString *const NSAccessibilityWindowResizedNotification = @"AXWindowResized";
NSString *const NSAppearanceNameAccessibilityHighContrastAqua = @"NSAppearanceNameAccessibilityAqua";
NSString *const NSAppearanceNameAccessibilityHighContrastDarkAqua = @"NSAppearanceNameAccessibilityDarkAqua";
NSString *const NSApplicationDidHideNotification = @"NSApplicationDidHideNotification";
NSString *const NSApplicationDidResignActiveNotification = @"NSApplicationDidResignActiveNotification";
NSString *const NSApplicationLaunchUserNotificationKey = @"NSApplicationLaunchUserNotificationKey";
NSString *const NSApplicationWillBecomeActiveNotification = @"NSApplicationWillBecomeActiveNotification";
NSString *const NSDisplayNameBindingOption = @"NSDisplayName";
NSString *const NSDisplayPatternBindingOption = @"NSDisplayPattern";
NSString *const NSFontNameAttribute = @"NSFontNameAttribute";
NSString *const NSFontSymbolicTrait = @"NSCTFontSymbolicTrait";
NSString *const NSFontTraitsAttribute = @"NSCTFontTraitsAttribute";
NSString *const NSImageHintCTM = @"NSImageHintCTM";
NSString *const NSImageNameApplicationIcon = @"NSApplicationIcon";
NSString *const NSImageNameFolder = @"NSFolder";
NSString *const NSMenuDidBeginTrackingNotification = @"NSMenuDidBeginTrackingNotification";
NSString *const NSMenuDidEndTrackingNotification = @"NSMenuDidEndTrackingNotification";
NSString *const NSMenuWillSendActionNotification = @"NSMenuWillSendActionNotification";
NSString *const NSMultipleValuesPlaceholderBindingOption = @"NSMultipleValuesPlaceholder";
NSString *const NSNoSelectionPlaceholderBindingOption = @"NSNoSelectionPlaceholder";
NSString *const NSNotApplicablePlaceholderBindingOption = @"NSNotApplicablePlaceholder";
NSString *const NSNullPlaceholderBindingOption = @"NSNullPlaceholder";
NSString *const NSObservedKeyPathKey = @"NSObservedKeyPath";
NSString *const NSObservedObjectKey = @"NSObservedObject";
NSString *const NSOptionsKey = @"NSOptions";
NSString *const NSPasteboardNameDrag = @"Apple CFPasteboard drag";
NSString *const NSPasteboardNameFind = @"Apple CFPasteboard find";
NSString *const NSPasteboardNameGeneral = @"Apple CFPasteboard general";
NSString *const NSPasteboardTypeHTML = @"public.html";
NSString *const NSPasteboardTypeRTF = @"public.rtf";
NSString *const NSPreferredScrollerStyleDidChangeNotification = @"NSPreferredScrollerStyleDidChangeNotification";
NSString *const NSPrintAllPages = @"NSPrintAllPages";
NSString *const NSPrintFirstPage = @"NSFirstPage";
NSString *const NSPrintLastPage = @"NSLastPage";
NSString *const NSScreenColorSpaceDidChangeNotification = @"NSScreenColorSpaceDidChangeNotification";
NSString *const NSSharingServiceNameAddToSafariReadingList = @"com.apple.share.System.add-to-safari-reading-list";
NSString *const NSSharingServiceNameComposeEmail = @"com.apple.share.Mail.compose";
NSString *const NSSystemColorsDidChangeNotification = @"NSSystemColorsDidChangeNotification";
NSString *const NSTextInputReplacementRangeAttributeName = @"NSTextInputReplacementRangeAttributeName";
NSString *const NSTouchBarItemIdentifierCandidateList = @"NSTouchBarItemIdentifierCandidateList";
NSString *const NSTouchBarItemIdentifierCharacterPicker = @"NSTouchBarItemIdentifierCharacterPicker";
NSString *const NSTouchBarItemIdentifierFlexibleSpace = @"NSTouchBarItemIdentifierFlexibleSpace";
NSString *const NSURLTagNamesKey = @"NSURLTagNamesKey";
NSString *const NSWindowDidChangeOcclusionStateNotification = @"NSWindowDidChangeOcclusionStateNotification";
NSString *const NSWindowWillMiniaturizeNotification = @"NSWindowWillMiniaturizeNotification";
NSString *const NSWorkspaceApplicationKey = @"NSWorkspaceApplicationKey";
NSString *const NSWorkspaceScreensDidSleepNotification = @"NSWorkspaceScreensDidSleepNotification";
NSString *const NSWorkspaceScreensDidWakeNotification = @"NSWorkspaceScreensDidWakeNotification";
NSString *const NSWorkspaceWillPowerOffNotification = @"NSWorkspaceWillPowerOffNotification";
NSString *const _kLSOpenOptionBackgroundLaunchKey = @"_kLSOpenOptionBackgroundLaunchKey";
NSString *const kCGDisplayStreamColorSpace = @"kCGDisplayStreamColorSpace";
NSString *const kCGDisplayStreamDestinationRect = @"kCGDisplayStreamDestinationRect";
NSString *const kCGDisplayStreamMinimumFrameTime = @"kCGDisplayStreamMinimumFrameTime";
NSString *const kCGDisplayStreamPreserveAspectRatio = @"kCGDisplayStreamPreserveAspectRatio";
NSString *const kCGDisplayStreamShowCursor = @"kCGDisplayStreamShowCursor";
NSString *const kCGDisplayStreamSourceRect = @"kCGDisplayStreamSourceRect";
NSString *const kCGDisplayStreamYCbCrMatrix = @"kCGDisplayStreamYCbCrMatrix";
NSString *const kCGDisplayStreamYCbCrMatrix_ITU_R_601_4 = @"ITU_R_601_4";
NSString *const kCGWindowBounds = @"kCGWindowBounds";
NSString *const kCGWindowIsOnscreen = @"kCGWindowIsOnscreen";
NSString *const kCGWindowLayer = @"kCGWindowLayer";
NSString *const kCGWindowName = @"kCGWindowName";
NSString *const kCGWindowNumber = @"kCGWindowNumber";
NSString *const kCGWindowOwnerName = @"kCGWindowOwnerName";
NSString *const kCGWindowOwnerPID = @"kCGWindowOwnerPID";
NSString *const kDADiskDescriptionDeviceModelKey = @"DADeviceModel";
NSString *const kDADiskDescriptionDeviceRevisionKey = @"DADeviceRevision";
NSString *const kDADiskDescriptionDeviceVendorKey = @"DADeviceVendor";
NSString *const kDADiskDescriptionMediaBSDNameKey = @"DAMediaBSDName";
NSString *const kDADiskDescriptionMediaRemovableKey = @"DAMediaRemovable";
NSString *const kDADiskDescriptionMediaSizeKey = @"DAMediaSize";
NSString *const kDADiskDescriptionMediaUUIDKey = @"DAMediaUUID";
NSString *const kDADiskDescriptionVolumeNameKey = @"DAVolumeName";
NSString *const kDADiskDescriptionVolumePathKey = @"DAVolumePath";
NSString *const kDADiskDescriptionVolumeUUIDKey = @"DAVolumeUUID";
NSString *const kLSSharedFileListLoginItemHidden = @"com.apple.loginitem.HideOnLaunch";
NSString *const kLSSharedFileListSessionLoginItems = @"com.apple.LSSharedFileList.SessionLoginItems";
NSString *const kMDItemWhereFroms = @"kMDItemWhereFroms";
NSString *const kODAttributeTypeAllAttributes = @"dsAttributesAll";
NSString *const kODAttributeTypeAltSecurityIdentities = @"dsAttrTypeStandard:AltSecurityIdentities";
NSString *const kODAttributeTypeMetaRecordName = @"dsAttrTypeStandard:AppleMetaRecordName";
NSString *const kODAttributeTypeRecordName = @"dsAttrTypeStandard:RecordName";
NSString *const kODRecordTypeUsers = @"dsRecTypeStandard:Users";
const unsigned char NSFontIdentityMatrix[64] = {0};   // __DATA
const unsigned char kDADiskDescriptionMatchVolumeMountable[64] = {0};   // __DATA_DIRTY
const unsigned char kDADiskDescriptionWatchVolumePath[64] = {0};   // __DATA_DIRTY
const unsigned char kLSSharedFileListItemBeforeFirst[64] = {0};   // __DATA
const unsigned char kLSSharedFileListItemLast[64] = {0};   // __DATA

@interface NSResponder : NSObject
@end
@interface NSView : NSResponder
@end
@interface NSWindow : NSResponder
@end
@interface NSPanel : NSWindow
@end
@interface NSControl : NSView
@end
@interface NSTextField : NSControl
@end
@interface ASWebAuthenticationSessionWebBrowserSessionManager : NSObject
@end
@implementation ASWebAuthenticationSessionWebBrowserSessionManager
STUB_SAFETY_NET
@end
@interface CWWiFiClient : NSObject
@end
@implementation CWWiFiClient
STUB_SAFETY_NET
@end
@interface IOBluetoothDevice : NSObject
@end
@implementation IOBluetoothDevice
STUB_SAFETY_NET
@end
@interface IOBluetoothDeviceInquiry : NSObject
@end
@implementation IOBluetoothDeviceInquiry
STUB_SAFETY_NET
@end
@interface IOBluetoothHostController : NSObject
@end
@implementation IOBluetoothHostController
STUB_SAFETY_NET
@end
@interface IOBluetoothL2CAPChannel : NSObject
@end
@implementation IOBluetoothL2CAPChannel
STUB_SAFETY_NET
@end
@interface IOBluetoothRFCOMMChannel : NSObject
@end
@implementation IOBluetoothRFCOMMChannel
STUB_SAFETY_NET
@end
@interface IOBluetoothSDPServiceRecord : NSObject
@end
@implementation IOBluetoothSDPServiceRecord
STUB_SAFETY_NET
@end
@interface IOBluetoothSDPUUID : NSObject
@end
@implementation IOBluetoothSDPUUID
STUB_SAFETY_NET
@end
@interface NSAccessibilityRemoteUIElement : NSObject
@end
@implementation NSAccessibilityRemoteUIElement
STUB_SAFETY_NET
@end
@interface NSAnimation : NSObject
@end
@implementation NSAnimation
STUB_SAFETY_NET
@end
@interface NSAppleEventDescriptor : NSObject
@end
@implementation NSAppleEventDescriptor
STUB_SAFETY_NET
@end
@interface NSButtonCell : NSObject
@end
@implementation NSButtonCell
STUB_SAFETY_NET
@end
@interface NSCandidateListTouchBarItem : NSObject
@end
@implementation NSCandidateListTouchBarItem
STUB_SAFETY_NET
@end
@interface NSCell : NSObject
@end
@implementation NSCell
STUB_SAFETY_NET
@end
@interface NSColorPanel : NSPanel
@end
@implementation NSColorPanel
@end
@interface NSColorSampler : NSObject
@end
@implementation NSColorSampler
STUB_SAFETY_NET
@end
@interface NSComboBox : NSTextField
@end
@implementation NSComboBox
@end
@interface NSCustomTouchBarItem : NSObject
@end
@implementation NSCustomTouchBarItem
STUB_SAFETY_NET
@end
@interface NSDraggingItem : NSObject
@end
@implementation NSDraggingItem
STUB_SAFETY_NET
@end
@interface NSFontDescriptor : NSObject
@end
@implementation NSFontDescriptor
STUB_SAFETY_NET
@end
@interface NSFontManager : NSObject
@end
@implementation NSFontManager
STUB_SAFETY_NET
@end
@interface NSGroupTouchBarItem : NSObject
@end
@implementation NSGroupTouchBarItem
STUB_SAFETY_NET
@end
@interface NSMatrix : NSControl
@end
@implementation NSMatrix
@end
@interface NSPathControl : NSControl
@end
@implementation NSPathControl
@end
@interface NSPopUpButtonCell : NSObject
@end
@implementation NSPopUpButtonCell
STUB_SAFETY_NET
@end
@interface NSPopover : NSResponder
@end
@implementation NSPopover
@end
@interface NSPrintInfo : NSObject
@end
@implementation NSPrintInfo
STUB_SAFETY_NET
@end
@interface NSPrintPanel : NSObject
@end
@implementation NSPrintPanel
STUB_SAFETY_NET
@end
@interface NSScriptClassDescription : NSObject
@end
@implementation NSScriptClassDescription
STUB_SAFETY_NET
@end
@interface NSScriptCommand : NSObject
@end
@implementation NSScriptCommand
STUB_SAFETY_NET
@end
@interface NSSegmentedControl : NSControl
@end
@implementation NSSegmentedControl
@end
@interface NSSharingServicePicker : NSObject
@end
@implementation NSSharingServicePicker
STUB_SAFETY_NET
@end
@interface NSSpellChecker : NSObject
@end
@implementation NSSpellChecker
STUB_SAFETY_NET
@end
@interface NSTableColumn : NSObject
@end
@implementation NSTableColumn
STUB_SAFETY_NET
@end
@interface NSText : NSView
@end
@implementation NSText
@end
@interface NSTitlebarAccessoryViewController : NSObject
@end
@implementation NSTitlebarAccessoryViewController
STUB_SAFETY_NET
@end
@interface NSToolbar : NSObject
@end
@implementation NSToolbar
STUB_SAFETY_NET
@end
@interface NSTouchBar : NSObject
@end
@implementation NSTouchBar
STUB_SAFETY_NET
@end
@interface NSUniqueIDSpecifier : NSObject
@end
@implementation NSUniqueIDSpecifier
STUB_SAFETY_NET
@end
@interface NSUserNotification : NSObject
@end
@implementation NSUserNotification
STUB_SAFETY_NET
@end
@interface NSUserNotificationCenter : NSObject
@end
@implementation NSUserNotificationCenter
STUB_SAFETY_NET
@end
@interface ODNode : NSObject
@end
@implementation ODNode
STUB_SAFETY_NET
@end
@interface ODQuery : NSObject
@end
@implementation ODQuery
STUB_SAFETY_NET
@end
@interface ODRecord : NSObject
@end
@implementation ODRecord
STUB_SAFETY_NET
@end
@interface ODSession : NSObject
@end
@implementation ODSession
STUB_SAFETY_NET
@end
@interface SFCertificatePanel : NSPanel
@end
@implementation SFCertificatePanel
@end
@interface SFUniversalLink : NSObject
@end
@implementation SFUniversalLink
STUB_SAFETY_NET
@end
